### ISSUE TITLE
PR+Merge branch doesnt get automatically deleted

### ISSUE THREAD

**Issue by TruDan** [SimonCropp/GitHubSync#290]
When using the CLI tool to sync repos using `autoMerge: true`, it creates a branch with a PR for the changes, then automatically merges it (this works fine). However once it's done, it leaves the branch still in the repository.
 
After some time this builds up and it's a pain to manually delete them one by one (x15 repos)
![screenshot](https://user-images.githubusercontent.com/983207/87518101-1f367e80-c680-11ea-809b-737a011336ec.png)

can you add an option for `keepMergeBranch: true/false` ? or otherwise make it auto delete the branch once it's done? There's no reason for it to stay.

Thanks!

**Comment by SimonCropp** [comment]
u can use "Automatically delete head branches "

![image](https://user-images.githubusercontent.com/122666/87523884-d7891480-c6ca-11ea-9ee1-0a50be93dc39.png)

**Comment by TruDan** [comment]
> u can use "Automatically delete head branches "
> 
> ![image](https://user-images.githubusercontent.com/122666/87523884-d7891480-c6ca-11ea-9ee1-0a50be93dc39.png)

Unfortuantely I don't think this won't work in our situation, we use PR's to merge from `staging`->`master`, but we want the `staging` branch to stay. (the GitHubSync is setup to sync to the `staging` branch.

It could work if it excludes 'protected branches' from that auto delete

**Comment by SimonCropp** [comment]
happy to accept a PR for this
