### ISSUE TITLE
Allow sync to support multiple source repositories

### ISSUE THREAD

**Issue by GeertvanHorrik** [SimonCropp/GitHubSync#48]
At the moment, RepoSync only supports a single source repository. Would you be interested if I add support for multiple source repositories?

E.g.

```
AddSourceRepository(string organization, string repository, string branch);
```

Then I can loop them backwards:

```
for (int i = _sourceRepos.Count - 1; i >= 0; i--)
{
    // clone files (if not already cloned)
}
```

**Comment by GeertvanHorrik** [comment]
I've made the changes locally, let me know if you are interested in a PR for this.

**Comment by SimonCropp** [comment]
@GeertvanHorrik sure submit a PR :)

**Comment by GeertvanHorrik** [comment]
This is done now.
